version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    container_name: social_net_db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env

  redis:
    image: redis:latest
    container_name: social_net_redis
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - "9000:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 100

  web:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    container_name: social_net_web
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db
      - redis